### ISSUE TITLE
Anti-Aliasing in automation editior

### ISSUE THREAD

**Issue by TheTravelingSpaceman** [LMMS/lmms#2688]
For me (a relatively new user), a immediately recognisable issue is that the interface is not as well rounded as other music production software. The biggest eye-sore was the aliasing of the automation editor graph. It's probably not that noticeable to users with proper HD screens, but since I'm a scrub with a 720p display, it's horrible.

![example](https://cloud.githubusercontent.com/assets/17950515/13899563/e0326612-edf9-11e5-93f0-fcbd1c3e881b.png)

I suggest (going to try and do myself) implementing anti-aliasing for displaying the graphs of the automation editor and wherever else needed.

**Comment by tresf** [comment]
Words like "horrible" are rude and don't help get buy in for features like this.

Also, please stop comparing us to other DAWs.  State the problem, any insight, etc and leave the opinions out please.

I agree, this would be a nice addition.

Best regards.

**Comment by TheTravelingSpaceman** [comment]
Apologies, I was only referring to the way it displays on my screen compared to a proper one(which most people probably have). It wasn't an attempt to insult anyone, just a way of describing an effect exaggerated by my bad screen. I will limit my vocabulary in the future for the more sensitive readers.

**Comment by musikBear** [comment]
:imp: devils lawyer : Will antializing in song-editor cause a higher cpu usage? 
If so, i would say no thank you.

**Comment by Umcaruje** [comment]
No, it shouldn't. We don't redraw the Patterns all the time, only when they are changed, so this shouldn't affect CPU usage at all.

**Comment by michaelgregorius** [comment]
Fixed with #2694.

**Comment by zonkmachine** [comment]
![hint](https://cloud.githubusercontent.com/assets/6368949/13907271/f02895f4-eeea-11e5-88c7-f9b06787baf7.png)

:+1:

**Comment by TheTravelingSpaceman** [comment]
Seems like there are colour inconsistencies in the shading when the graph changes from a cure to a straight line:
![colors](https://cloud.githubusercontent.com/assets/17950515/13918218/6debc96a-ef6e-11e5-8dd3-a773145ddd2a.png)

**Comment by tresf** [comment]
@TheTravelingSpaceman good catch.  Some of this code has recently changed (f136ba3).  Tagging @Umcaruje in case he has any insight.

If you reset your code base to before f136ba3 (i.e. `git reset --hard b7d5b2d`) does this strange rendering still occur?

My initial instinct is that the gradients are being rendered from the wrong spot, but if that were the case, the rendering bug would exist before the antialising hint was introduced.

**Comment by TheTravelingSpaceman** [comment]
I just reset my code base and added the line to introduce anti-aliasing.
Error still persists.

**Comment by tresf** [comment]
@TheTravelingSpaceman Thanks for testing, much appreciated.

I assume you've also moved your `~.lmmsrc.xml` file as well to make sure no strangeness is happening with the theme file?

**Comment by TheTravelingSpaceman** [comment]
Nope, I apologise for being a bit useless. First time I'm using github and working on any openSource project. This seems a bit over my head for now. Would love to contribute in the future. Still learning.

**Comment by tresf** [comment]
@TheTravelingSpaceman you are being very helpful actually.

The aforementioned XML file stores your LMMs preferences.  Old versions of this file can cause graphic anomalies.  Yours are unlikely to be caused by this file, but if you close LMMS and move it, it will regenerate with the details settings and eliminate it from the troubleshooting process. :)

**Comment by musikBear** [comment]
> No, it shouldn't. We don't redraw the Patterns all the time, only when they are changed, so this shouldn't affect CPU usage at all

:+1:

**Comment by Umcaruje** [comment]
I actually did a more complex patch on a local branch to make a PR for this:
```diff
diff --git a/src/gui/AutomationPatternView.cpp b/src/gui/AutomationPatternView.cpp
index 71fd0d6..f88d5d1 100644
--- a/src/gui/AutomationPatternView.cpp
+++ b/src/gui/AutomationPatternView.cpp
@@ -305,6 +305,8 @@ void AutomationPatternView::paintEvent( QPaintEvent * )
        lin2grad.setColorAt( 0.5, col );
        lin2grad.setColorAt( 0, col.darker( 150 ) );
 
+       p.setRenderHints( QPainter::Antialiasing, true );
+ 
        for( AutomationPattern::timeMap::const_iterator it =
                                                m_pat->getTimeMap().begin();
                                        it != m_pat->getTimeMap().end(); ++it )
@@ -312,7 +314,7 @@ void AutomationPatternView::paintEvent( QPaintEvent * )
                if( it+1 == m_pat->getTimeMap().end() )
                {
                        const float x1 = x_base + it.key() * ppt /
-                                               MidiTime::ticksPerTact();
+                                               MidiTime::ticksPerTact() + 0.5;
                        const float x2 = (float)( width() - TCO_BORDER_WIDTH );
                        if( x1 > ( width() - TCO_BORDER_WIDTH ) ) break;
                        if( gradient() )
@@ -331,7 +333,7 @@ void AutomationPatternView::paintEvent( QPaintEvent * )
                {
                        float value = values[i - it.key()];
                        const float x1 = x_base + i * ppt /
-                                               MidiTime::ticksPerTact();
+                                               MidiTime::ticksPerTact() + 0.5;
                        const float x2 = x_base + (i + 1) * ppt /
                                                MidiTime::ticksPerTact();
                        if( x1 > ( width() - TCO_BORDER_WIDTH ) ) break;
@@ -348,6 +350,8 @@ void AutomationPatternView::paintEvent( QPaintEvent * )
                delete [] values;
        }
 
+       p.setRenderHints( QPainter::Antialiasing, false );
+
        p.resetMatrix();
        
        // bar lines

```

But I ran on the color issues. They are there because we draw the patterns using a loop, that adds up a lot of rectrangles one after another. Now, these rectrangles have odd values, like a width of `0,4769` or something like that, which causes the renderer to draw half-transparent pixels to compensate when antialiasing. Now I fixed that a bit by increasing the x coordinated by 0,5, but that doesn't help when the pattern gets zoomed in. 
![screenshot from 2016-03-19 22 08 54](https://cloud.githubusercontent.com/assets/6282045/13925590/26eee5b8-ef89-11e5-99d2-70a747bde4d7.png) ![screenshot from 2016-03-19 20 18 27](https://cloud.githubusercontent.com/assets/6282045/13925592/2a063e72-ef89-11e5-8593-c3e73364156c.png)
![screenshot from 2016-03-19 22 10 46](https://cloud.githubusercontent.com/assets/6282045/13925617/448015d4-ef89-11e5-93a5-4d9303833bf1.png)

If we want real antialiasing to happen, we'll need to use `drawPolygon` or something similar, instead of drawing rectrangles one after another. Same thing occurs in `AutomationEditor` as well.

**Comment by tresf** [comment]
Great investigation @Umcaruje.  You're completely right, better drawing code would use [fill rather than drawing a bunch of rectangles](http://stackoverflow.com/a/19356908/3196753).

I assume rounding to the nearest pixel doesn't help either?

**Comment by Umcaruje** [comment]
Well, it would just be a lot of rectangles chained together, it still wouldn't look as smooth as it could be if it was properly drawn.

**Comment by musikBear** [comment]
Just a thought
It is actually not the filled shape thats represent the automation. Its only the peak-values:
![automatline](https://cloud.githubusercontent.com/assets/6662066/13950558/0494d7f4-f02c-11e5-9bfe-c389b24a6bf6.png)
Perhaps *that* was a way to go? I believe that pro-tools and Reaper also only represent the flow of automation with a line. I cant remember how FLS does it, but thats not all that relevant. How about doing it in lmms?

**Comment by tresf** [comment]
> Perhaps that was a way to go? I believe that pro-tools and Reaper also only represent the flow of automation with a line. I cant remember how FLS does it, but thats not all that relevant. How about doing it in lmms?

This probably isn't a place to decide how to re-design the automation tracks.  Had it been, I would come back with my typical "draw automations over the tracks themselves" canned response.

>  that would remove any need for antialiazing too.

Are you sure? Why wouldn't we still have this aliasing problem?

**Comment by TheTravelingSpaceman** [comment]
I don't think it would remove need for anti-aliasing... Maybe make it easier but not remove it. Also, as a general rule I don't like the idea of making design changes based on the fact that it would be easier to implement(Easily said since I'm not the one doing the implementing).

**Comment by tresf** [comment]
> I don't think it would remove need for anti-aliasing... 

:+1:

**Comment by musikBear** [comment]
if you lit one pixel of each pixel-pos in screen, for a curve, that is the actual flow. I would not AA an actual measured flow, but this is just tedious derailing, since tresf already has dismissed the proposal for a single line-representation.

**Comment by michaelgregorius** [comment]
@musikBear Why wouldn't you antialias that line? If you only paint one pixel per coordinate of the y axis this is exactly what will give you aliasing:
https://courses.engr.illinois.edu/ece390/archive/archive-f2000/mp/mp4/anti.html

**Comment by TheTravelingSpaceman** [comment]
@Umcaruje I recently looked at the anti-aliasing problem again and applied your code changes too see why it didn't work. I found it to work almost perfectly (without the +0.5 lines). It may be that it's only less noticeable now because of the new colour scheme. Any comments?

**Comment by zonkmachine** [comment]
> It may be that it's only less noticeable now because of the new colour scheme.

Yes. If you switch to the old theme named classic, you'll notice that it's the same now. Sorry!

**Comment by Umcaruje** [comment]
>@Umcaruje I recently looked at the anti-aliasing problem again and applied your code changes too see why it didn't work. I found it to work almost perfectly (without the +0.5 lines).

Did you try zooming in? it works perfectly until you change the zoom

**Comment by TheTravelingSpaceman** [comment]
After many hours of trying different things I am quite happy with what happens when the following code changes are applied. It solves the anti-aliasing issue and by drawing polygons instead of rectangles and uses the anti aliasing hint. I also made sure there are no shading inconsistencies. 


For some reason however it sometimes doesn't want to draw an automation that is not linked to anything. I believe it is because the values ranges are between 0 and 1 and not 0 and 100 but this is also the case for the master branch and for some reason it works. Can anyone shed some light on it?

Before:
![before](https://cloud.githubusercontent.com/assets/17950515/23331380/8767763a-fb6d-11e6-8501-dcb36bd9b99d.png)
After:
![after](https://cloud.githubusercontent.com/assets/17950515/23331379/8765e0b8-fb6d-11e6-9487-cb6f924aac50.png)




```diff
diff --git a/src/gui/AutomationPatternView.cpp b/src/gui/AutomationPatternView.cpp
index 85d8d53..6c2634f 100644
--- a/src/gui/AutomationPatternView.cpp
+++ b/src/gui/AutomationPatternView.cpp
@@ -291,6 +291,7 @@ void AutomationPatternView::paintEvent( QPaintEvent * )
        lin2grad.setColorAt( 0.5, col );
        lin2grad.setColorAt( 0, col.darker( 150 ) );
 
+       p.setRenderHints( QPainter::Antialiasing, true );
        for( AutomationPattern::timeMap::const_iterator it =
                                                m_pat->getTimeMap().begin();
                                        it != m_pat->getTimeMap().end(); ++it )
@@ -315,25 +316,37 @@ void AutomationPatternView::paintEvent( QPaintEvent * )
                float *values = m_pat->valuesAfter( it.key() );
                for( int i = it.key(); i < (it + 1).key(); i++ )
                {
-                       float value = values[i - it.key()];
+                       float x1value = values[i - it.key()];
+                       float x2value = values[i - it.key() + 1];
+                       if (i+1 == (it + 1).key()) x2value = x1value; //Catches last value not being there
+
                        const float x1 = x_base + i * ppt /
                                                MidiTime::ticksPerTact();
                        const float x2 = x_base + (i + 1) * ppt /
                                                MidiTime::ticksPerTact();
                        if( x1 > ( width() - TCO_BORDER_WIDTH ) ) break;
 
+                       //Creates Polygon
+                       QPainterPath path;
+                       path.moveTo(QPoint(x1,0));
+                       path.lineTo(QPoint(x1,x1value));
+                       path.lineTo(QPoint(x2,x2value));
+                       path.lineTo(QPoint(x2,0));
+                       path.lineTo(QPoint(x1,0));
+
                        if( gradient() )
                        {
-                               p.fillRect( QRectF( x1, 0.0f, x2 - x1, value ), lin2grad );
+                               p.fillPath(path,lin2grad);
                        }
                        else
                        {
-                               p.fillRect( QRectF( x1, 0.0f, x2 - x1, value ), col );
+                               p.fillPath(path,col);
                        }
                }
                delete [] values;
        }
 
+       p.setRenderHints( QPainter::Antialiasing, false );
        p.resetMatrix();
        
        // bar lines
```

**Comment by zonkmachine** [comment]
Cool! Can you submit this as a pull request?
https://github.com/LMMS/lmms/wiki/Submitting-a-patch

**Comment by zonkmachine** [comment]
Closed in #3386
