### ISSUE TITLE
Presets with peak controller crash LMMS after previewing

### ISSUE THREAD

**Issue by LostPr3acherEDM** [LMMS/lmms#3897]

**Comment by LostPr3acherEDM** [comment]
Some specifics:
Version: 1.2.0-rc4 (beta) and ALL PREVIOUS NON-BETA ("STABLE") VERSIONS AS WELL. 
This problem has never failed to faithfully occur for me, and I've used both 32 bit & 64 bit 
versions (on the correct systems, don't worry). 
_____________________________________________________
I'm not a coder, though in auld lang syne I have made hewo.c successfully lol. My issue is that I'm
unsure as to whether I'm unaware of a patch or fix that perhaps already exists, or that I'm unaware that I'm doing something wrong to begin with in the program. However, seeing as this is a simple matter of dragging a 3xOscillator preset I'd saved prior into an editor, this seems pretty straightforward to me, and I don't think I've done it wrong. It simply crashes the program, and I've no clue as to how. 
Please let me know if I need to quit looking for a fix (because it hasn't been reached yet on the list of things to fix) or whether I've simply been looking in all the wrong places. 

Thank you for your support of this program that has enabled me to change my life.
I'm an artist, and creative people must create to be happy and sane. In my current life situation, I would not be able to do that to the tune of hundreds of dollars for Ableton/FL/Logic/etc.
I am aware that a free product falls under the "beggars can't be choosers" category, and I'm well aware that I should expect some issues. 

This particular issue, though, is one which drives me nuts.

Thanks y'all.

M. Rodgers

**Comment by PhysSong** [comment]
Can you provide your system informations and steps to reproduce?

**Comment by PhysSong** [comment]
@LostPr3acherEDM What Is your OS and which directory did you save your preset in?

**Comment by LostPr3acherEDM** [comment]
Sys Info:
Win 10 Pro
Version: 1511
OS Build 10586.420
Processor: AMD FX(tm)-6100 Six-Core Processor 3.30 GHz
Installed RAM: 16.0 GB
System Type: 64 bit for both OS and processor.

Steps to reproduce:
Drag a 3xOscillator from instrument plugins. Set all signals to white noise. 
Go to FX and drag in a peak controller. Save preset. 
I saved to the default folder that LMMS provided upon clicking save:
"C:\Users\(my user name)\lmms\presets\TripleOscillator"
Save project. Exit LMMS.
Start LMMS again, open up the default BBE and attempt to drag your preset you save previously into it and IMMEDIATELY upon attempting to save the project again, sometimes before, it crashes. I'm clueless.

**Comment by LostPr3acherEDM** [comment]
I'll be back momentarily to see what you typed. (smoke break) Thank you so much for this amazingly fast response. I truly appreciate it.

**Comment by PhysSong** [comment]
Does your username contain non-ASCII characters?

**Comment by LostPr3acherEDM** [comment]
My username consists of one word in English followed by a space and then around eight numbers. Do numerals count within ASCII? I used to make ASCII art lol, but I don't recall the specifics of what is or is not ASCII.

**Comment by PhysSong** [comment]
Then howabout preset file name? And what happens if you drop a preset or project file into song editor?

**Comment by LostPr3acherEDM** [comment]
![filename](https://user-images.githubusercontent.com/32978443/31850990-12459af2-b62b-11e7-8554-77d9c05dbec4.png)

**Comment by LostPr3acherEDM** [comment]
![savethencrash](https://user-images.githubusercontent.com/32978443/31851012-8c356266-b62b-11e7-88df-0f98c9260c5c.png)

**Comment by LostPr3acherEDM** [comment]
When I drag native presets onto the screen, I can save my work and nothing wrong occurs. However, if I dare attempt to drag one of my OWN presets and then save the program, it crashes every single time without fail.

**Comment by PhysSong** [comment]
Can you open loaded instrument before saving? If so, does it sound as expected?

**Comment by LostPr3acherEDM** [comment]
I just tried. I made the preset, saved it, refreshed the presets menu and dragged it back into the editor and as soon as I tried hitting play, it crashed.

**Comment by gi0e5b06** [comment]
Confirmed. On Linux too.
```
Thread 1 "lmms" received signal SIGSEGV, Segmentation fault.
ControllerView::paintEvent (this=0x555556f4f160) at lmms/src/gui/widgets/ControllerView.cpp:210
210             p.drawText( 5, 54, model()->displayName() );
```
(no no-ascii character was used)

**Comment by gi0e5b06** [comment]
model() is null.

**Comment by PhysSong** [comment]
@LostPr3acherEDM If you load default TripleOscillator and save it to preset, does LMMS crash? If so, what if you save your own preset to the built-in preset directory?

**Comment by musikBear** [comment]
not able to reproduce on rc4 win32
@LostPr3acherEDM try this
* shut down lmms
* shut down pc *completely* -**not sleep**
Wait a mins
* start pc & lmms
* open myPresets | trippleOSC
* right-click on the preset that cause the crash
* select 'open in song-editor' from context menu

what happen?

Now try to drag it in
what happen?

**Comment by tresf** [comment]
@gi0e5b06 since you can reproduce this, can you please help document the steps that get this to happen each time and help provide a proper backtrace?  I too cannot reproduce this bug, we need some help. :)

**Comment by tresf** [comment]
... and @LostPr3acherEDM thanks for the kind words and well described bug report.  If @gi0e5b06 can trace the crash, we should be able to fix this in time for `stable-1.2`.

**Comment by gi0e5b06** [comment]
@tresf I just followed the given instructions.
The backtrace of the segfault doesn't help because it's in paintEvent().
However, the backtrace of the constructor is:

stack trace:
```
  lmms/lmms : ControllerRackView::onControllerAdded(Controller*)+0x47
  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 : QMetaObject::activate(QObject*, int, int, void**)+0x639
  lmms/lmms : Song::controllerAdded(Controller*)+0x42
  lmms/lmms : Song::addController(Controller*)+0xfe
  lmms/plugins/libpeakcontrollereffect.so : PeakControllerEffect::PeakControllerEffect(Model*, Plugin::Descriptor::SubPluginFeatures::Key const*)+0xa8
  lmms/plugins/libpeakcontrollereffect.so : lmms_plugin_main()+0x31
  lmms/lmms : Plugin::instantiate(QString const&, Model*, void*)+0xb5
  lmms/lmms : Effect::instantiate(QString const&, Model*, Plugin::Descriptor::SubPluginFeatures::Key*)+0xc
  lmms/lmms : EffectChain::loadSettings(QDomElement const&)+0x48a
  lmms/lmms : SerializingObject::restoreState(QDomElement const&)+0x12
```
The model is not set after that.
Related part of the preset:
```
      <fxchain enabled="1" numofeffects="1">
        <effect gate="0" autoquit_syncmode="0" autoquit_numerator="4" name="peakcontrollereffect" wet="1" autoquit="1" autoquit_denominator="
4" on="1">
          <peakcontrollereffectcontrols mute="0" abs="1" effectId="346664770" base="0.5" amountmult="1" treshold="0" decay="0" amount="1" att
ack="0"/>
          <key/>
        </effect>
      </fxchain>
```

**Comment by eagles051387** [comment]
Is there a reason you are not on the latest version of windows 10 which is version 1703 currently? It might be potentially that this issue does not occur on the latest win 10 version

**Comment by PhysSong** [comment]
@gi0e5b06 Did you put a peak controller in your preset?

**Comment by gi0e5b06** [comment]
@eagles051387 The issue occurs on Linux too. It's related to Lmms, not to the OS.

@PhysSong Yes, I followed the instructions given by @LostPr3acherEDM to confirm the bug.

It looks like the peak controller is restored in an invalid state.

**Comment by PhysSong** [comment]
Maybe related: #193

**Comment by PhysSong** [comment]
Wait, `ControllerView::paintEvent()` isn't in our code. It is added by @gi0e5b06 in gi0e5b06/lmms@a0bb009.
@gi0e5b06 Can you reproduce this with clean `stable-1.2` build?

**Comment by PhysSong** [comment]
Tested. add by context menu works properly. After you preview a preset, however, the peak controller created by previewing doesn't get deleted.

**Comment by PhysSong** [comment]
And there's one more issue: assume that issue is fixed. However, the peak controller from preview track will be saved if you save during previewing, the controller will be saved. The saved file won't be open correctly because of corrupted peak controller.

**Comment by BaraMGB** [comment]
Does it make sense to save a peak controller with a preset?

**Comment by PhysSong** [comment]
Yes. For example, user might save that as a sidechain signal.

**Comment by PhysSong** [comment]
The simplest way is not to instantiate peak controller when previewing. It seems already implemented, but broken now. I'm going to fix that.

**Comment by musikBear** [comment]
@PhysSong this 'preview' is also happening with VSTs **effects**. The VST UI will open is you prehear a preset, where a VST *effect* is placed on the FX-tab.
This will result in an orphan remoteVST, that only can be closed down in TM, so its a genuine mem.leak
Half of the issue was #300 (VST*instruments*), but the *effect-part* var not solved in #1587 (300 was solved in 1587).

**Comment by gi0e5b06** [comment]
Fixed. Also a few other bugs in the file browser.
https://github.com/gi0e5b06/lmms/commit/52eed29a99043b8725acde20ae75e992cb8f0125
My new git assistant @Umcaruje will make a nice PR from that (or not). He volunteered on Discord.

@PhysSong For saving, nothing is done. However, I added a m_savingProject bool that works like m_loadingProject.

**Comment by PhysSong** [comment]
> but the effect-part var not solved in #1587 (300 was solved in 1587).

@musikBear If it can be reproduced, I'll re-open that. It may be added into 1.2.0 milestone if needed.
