### ISSUE TITLE
SF2 Player does not properly handle loop points

### ISSUE THREAD

**Issue by Hey-Holokin** [LMMS/lmms#4386]
Version: 1.2.0rc5 64-bit, untested in prior versions
Operating System: Windows 10 Home Edition, 64-bit
Might specify on: #4341 

I was looking to create a fan-made Mega Man X VGM track, and upon loading the soundfont I had downloaded into the SF2 player and playing a note in most of the patches, I realized these patches don't loop properly.
The soundfont in question: http://www.williamkage.com/snes_soundfonts/mega_man_x_soundfont.zip
I'm uncertain if this happens with other soundfonts, I just tried loading a different one into the soundfont player and it outright wouldn't load.

**Comment by DeRobyJ** [comment]
Confirmed on 1.2.0 RC6 64-bit on windows using this http://www.williamkage.com/snes_soundfonts/final_fantasy_6_soundfont.zip

It seems to randomly set loop points at start and end of the sample.

This, however, it is not our bug, it's a FluidSynth bug.
Here is a discussion about it:
https://github.com/FluidSynth/fluidsynth/issues/149
Apparently it should be fixed as of 1.1.7, https://github.com/FluidSynth/fluidsynth/releases/tag/v1.1.7

So to fix this we need to update FluidSynth.

**Comment by maxlefou** [comment]
Same problem here with this soundfont here: https://musical-artifacts.com/artifacts/21/Super_Mario_World.zip

Tried to fiddle with polyphone just in case, but no chance. Plus, the sf behaves as expected in polyphone... :(

Tested on 1.2.0rc5 64-bit on Windows 10

**Comment by maxlefou** [comment]
Same problem here with [this soundfont here](https://musical-artifacts.com/artifacts/21/Super_Mario_World.zip). I guess the rc8 still doesn't have the update...

**Comment by zonkmachine** [comment]
I did a quick test and it looks like this is fixed in master with libfluidsynth2. Closing, please reopen if you can replicate the issue on the master branch with libfluidsynth2.
