### ISSUE TITLE
The cloned patterns do not move in the song editor.

### ISSUE THREAD

**Issue by Gabrielxd195** [LMMS/lmms#4777]
I recently discovered that in the song editor you can create rhythm patterns, and this is super cool, for the persuasions. but I found a problem and that is that when I want to clone a pattern or a group of patterns, it is impossible to move them from their place. It's something like this.

![clonacion de patrones en el editor de cancion](https://user-images.githubusercontent.com/26127693/51357039-0947fd80-1a8b-11e9-8623-d264683a40ef.gif)

you can copy and paste the patterns using the '' ctrl + drag '' key but once the steps of the patterns have been cloned, they do not move from their place either with the cursor or with the selection tool. I think this should be reviewed. greetings and thanks.

**Comment by musikBear** [comment]
> discovered that in the song editor you can create rhythm patterns, and this is super cool

ehrr Why?
Why is it 'cooler' than to make the percussion properly in B&B?
Imo the feature is confusing, and not intuitive

**Comment by musikBear** [comment]
@Gabrielxd195 Wrote
> create more repetitive rhythms without so many variations in the percussion.

True, but at the 'cost' of one more instrument: One HHat01in B&B for the base-rythm, *and* one HHat01 in SE. for the variations, but infact a very variated beat could be build from 'LEGO' brick-sized B&B-lines. The smaller the item, the more permutations can be made, but dumb-me discussion about usage strategy. If the blocks wont move, its a bug :p

**Comment by musikBear** [comment]
@ JohannesLorenz is correct. The mouse-grab-area is too tiny in low magnification. The BB-ised SE blocks *can* be moved, when they are magnified enough for an area in the very top of the TCO -Kin of a 'hot-bar'. They block also move correctly using SH+INS/DEL. 
The limitation of this 'hot-bar' for mouse interactions, also influence context-meny copy and paste.
Neither is possible outside the 'hot-bar' ..or if you like -with mouse touching any of the tog-gable buttons. They will only change state

**Comment by noahb01** [comment]
Is it even worth keeping this as a feature? I can’t see why you wouldn’t just use a BB-Track (for repetitive stuff) or just an Instrument-Track (for nonrepetitive stuff). IMO the Song-Editor should be used for building the structure of the song, not for actually placing notes. That’s what the BB- and Instrument-Tracks are for.

**Comment by Gabrielxd195** [comment]
> Is it even worth keeping this as a feature? I can’t see why you wouldn’t just use a BB-Track (for repetitive stuff) or just an Instrument-Track (for nonrepetitive stuff). IMO the Song-Editor should be used for building the structure of the song, not for actually placing notes. That’s what the BB- and Instrument-Tracks are for.

Any feature that improves the workflow and facilitates certain lmms functions will be worth more than the penalty, and we should even correct the errors of those features. the one that you do not use the s.e. for the edition of patterns does not make it useless, simply everyone uses what conbiene. the important thing is that lmms have several options for how to compose, in my case I use bb editor and the s.e. for both, I do not see anything wrong with that.

> 
> I also find them rather annoying when trying to use the program because they get created every time you click on an empty section of an Instrument-Track.

Sometimes it's annoying, but that's not why it should be removed, but corrected.

> 
> Ultimately, we use a multi-window UI, so each window should have its own purpose. No need to combine the Song-Editor and BB-Track.

So it is friend, each window has its own purposes, but if it is necessary to break '' philosophies '' to improve the program, then that maintenance of this feature is corrected and the one who does not want to use it, well, not use it, but be available for those who want to use it. regards

**Comment by musikBear** [comment]
@Gabrielxd195 I definitively recognize your point of view, and in general i agree. But this feature is 'skewed' in a non intuitive way. 
I remember that it was reported as a *real* bug when it first appeared, and i still see it as a kind of fluke, not a feature. The worst thing that can be said about it, is that it is against the 'atomic-law'. You get <1 generator that participate in the same event. The effect is, that if we look at this scenario as a DB situation, the DB-admin would have to make <1 *identical* edits to reach a steady-state!
*That* is intrinsic *wrong*!
...However
It is NOT that kind of situation, and differences are not unwanted on the contrary actually, because fatal differences would here be *variations* ! ...
Variations are good in music..
*sigh*
But still this "Identical by two" It bothers me.
Then the next ugly one pops up:
*If* this has to be preserved, it would need *extra coded functions*, in order to be able to get the same behaviour as the TCOs in general.
Functions that would break the Super-to-child hierarchy, so it would be a hit against the OOP 'rules' (and cost dev time...)
Inside that wormcan lies ugly stuff like overcomplicated code-structure -Eg the program gets more complicated, and hence more difficult to bug-hunt
A "TCO"... but not in all circumstances, some with special heuristics *Argggh*
Its a distasteful cookie..
