### ISSUE TITLE
LMMS quits unexpectedly when loading a project that uses Carla 2.3.0-alpha1

### ISSUE THREAD

**Issue by jeffbicca** [LMMS/lmms#5692]
### Bug Summary
LMMS quits itself when loading a project that is using Carla 2.3.0-alpha1. 
LMMS was loading the project fine since yesterday. After, I've received an update of Carla and since then LMMS is crashing with the attached log.

#### Steps to reproduce
Load any project that uses Carla 2.3.0-alpha1

#### Expected behavior
To LMMS load the track correctly and don't crash.

#### Actual behavior
LMMS is quitting unexpectedly.

#### Affected LMMS versions
lmms-1.2.2-linux-x86_64.AppImage

Running LMMS in Ubuntu 19.10.
Running `carla --version` shows me the following information:
```
Using Carla version 2.3.0-alpha1
  Python version: 3.7.5
  Qt version:     5.12.4
  PyQt version:   5.12.3
  Binary dir:     /usr/lib/carla
  Resources dir:  /usr/share/carla/resources
```

#### Logs
<details>
  <summary>Click to expand</summary>
<pre>
Carla appears to be installed on this system at /usr/lib[64]/carla so we'll use it.
Jack appears to be installed on this system, so we'll use it.
Starting using X11Embed protocol.
unique ID: FV2l
RemotePlugin::DebugMessage: inputs: 2  output: 2
RemotePlugin::DebugMessage: creating editor
RemotePlugin::DebugMessage: editor successfully created
Starting using X11Embed protocol.
unique ID: FV2l
RemotePlugin::DebugMessage: inputs: 2  output: 2
RemotePlugin::DebugMessage: creating editor
RemotePlugin::DebugMessage: editor successfully created
/tmp/.mount_lmms-1IbqAnR/usr/bin/lmms.real: symbol lookup error: /tmp/.mount_lmms-1IbqAnR/usr/lib/lmms/libcarlabase.so: undefined symbol: carla_get_library_filename
</pre>
</details>

**Comment by PhysSong** [comment]
How did you install Carla?

**Comment by jeffbicca** [comment]
@PhysSong I am installing and upgrading Carla directly with apt from the KXStudio repositories as explained here: https://kx.studio/Repositories

**Comment by jeffbicca** [comment]
More informations about this: I've installed the package `carla-git`, which I suppose it grabs the most recent tagged version off the Carla git repository.
For now I've uninstalled and installed the package `carla` (which points to version 2.1.1) for me to be able to reopen my project again and keep the work going on.

I think it is interesting in keeping this issue opened as it is sounding to me as a breaking change for LMMS in a near future.

**Comment by PhysSong** [comment]
Thanks for the information. We will keep track of it.

**Comment by PhysSong** [comment]
It seems like `carla_get_library_filename` has been renamed to `carla_standalone_get_library_filename` in https://github.com/falkTX/Carla/commit/0fad472b59033701cab2c89df4816decb1a121fa.
@falkTX Should we change anything to follow the changes?

**Comment by falkTX** [comment]
No, not yet. I am doing some changes in the develop branch for testing how a host-friendly library will work. They are not finalized yet.

**Comment by falkTX** [comment]
That is to say, I might revert those renames. Not sure yet.

**Comment by falkTX** [comment]
This should be working as normal now

**Comment by tank-trax** [comment]
Debian Buster 10.6
LMMS 1.2.2
Carla 2.3.0-alpha2

I get this error

`lib/lmms/libcarlabase.so: undefined symbol: carla_get_library_filename`

**Comment by falkTX** [comment]
That was something temporary while I was investigating changes to Carla's API.
It has already been "fixed", just update it once again.

**Comment by tank-trax** [comment]
same thing still happens with carla-git version 5:2.3~alpha2+git20201119

carla version 5:2.2.0+git20201005 is OK

**Comment by sbeitelmal** [comment]
Hey I'm facing the same problem. 
I'm getting the following error when using Carla version 2.3.0-alpha2 and trying to use it in LMMS 1.2.2 (this version of Carla is the current one when using the Carla-git from the repository)

undefined symbol: Carla_get_library_filename

The error is resolved if I use the Carla version 2.2.0 but the current version of Carla vst wine isn't compatible with 2.2.0 which is my primary usage of Carla 





> That was something temporary while I was investigating changes to Carla's API.
> It has already been "fixed", just update it once again.


I am unclear on what to update here to get this problem fixed, Carla, or LMMS? and how would I go about doing that without breaking things. As when I tried to build Carla or LMMS from source LMMS did not detect Carla. I would really appreciate any help on how to fix this since I'm an absolute newb.

**Comment by falkTX** [comment]
This was bothering me, so I went to check.
My assumptions were wrong in thinking I really had this fixed.
So the *real* fix for carla-git is in `2.3~alpha2+git20201121.2`

**Comment by sbeitelmal** [comment]
thank you for responding!
is there a way to install this specific version through the repository or should i just wait for the changes to be committed to the repository version, because as I said i faced some pretty bad compatibility issues when i tried to install from source, probably due to some mistake on my side.

**Comment by falkTX** [comment]
you can just wait and I will update it.
sadly other stuff is broken at the moment in git, so the build fails. will need to deep deeper into it later.

**Comment by tank-trax** [comment]
the carla-git version is stable now, thanks!

**Comment by falkTX** [comment]
hah, great, thanks for testing!
didnt even have to ask here haha.

**Comment by hibobmaster** [comment]
In LMMS1.3.0-alpha.1, when press on the _show GUI_ button in Carla Ratch or Carla Patchbay, LMMS will get no response sometimes.
If i use Carla to load VST3, Carla GUI will get no response and i have to delete this track
Carla version: v2.2.0
Platform: windows10-20H2-19042.685
VST3 sample file:  https://csueducn-my.sharepoint.com/:u:/g/personal/bobmaster_csu_edu_cn/EfBY7gntMZtEm2OLc0R-IJsBPcJ_THa2f7JXC1tApbzBLw?e=ArtxnB

**Comment by bosseyes** [comment]
lmms: 1.3.0-alpha.1
carla: v2.2.0 (from here https://kx.studio/Applications:Carla)
platform: windows 10.0.18363 Build 18363

I set the system path variable as described here: https://github.com/LMMS/lmms/pull/5713
I moved the carla.dll from the lmms plugins/optional folder to the plugins folder.

-> LMMS crashes when creating new Carla Rack or Patchbay...

**Comment by ITheP** [comment]
Tried with LMMS 1.3.0alpha + latest Carla here too - same thing - try and add Carla Rack or Patchbay and crashes out
