### ISSUE TITLE
support RQ -crash behavior

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms#864]
win 32
1.0.2 
I label this a 'support RQ', even though its about crashing. 
LMMS does purely in plugins. Especially chorus. Blue-Cat has a very good plugin. 
Here comes the problem
When the plugin is loaded from default folder, it loads fast and correct. Works perfectly.
The project is saved.
When _this_ saved project is reopend, lmms freezes (80% loaded)
The plugin needs to removed manually from the xml-file
I do not understand why the actual 'import'-load, goes without problems and with a working plugin, but reopen fails, and even render the project useless (unless the xml is edited). If anyone could explain or know the reason for that kind of behavior, perhaps the issue could be solved. 
In a way this question could be expressed:
Does initial loading differ in _method_ from _re_loading. If so, why?

**Comment by Umcaruje** [comment]
@musikBear is this still an issue? There have been changes in how VST data is handled.

**Comment by tresf** [comment]
We can probably consolidate all VST crashes into a mega-issue and then close them individually afterwards since fixing a chunk of VST data for one may fix it for others as well.  IIRC, not much has been fixed in terms of VST support, so if this crashed in 1.0, it will likely crash in 1.1 and 1.2.

-Tres

**Comment by musikBear** [comment]
@Umcaruje im still on 1.1.3 - if you can make a binary Master x32, i will test the blue-cat, and others with this behavior

**Comment by Spekular** [comment]
@musikbear Here's a link to Windows 32 and 64 bit installers, thanks to Umcaruje: https://drive.google.com/folderview?id=0B49dcRGtm8vJcV9LU0xqZW81QjQ&usp=sharing

**Comment by musikBear** [comment]
did update on a different thread, but perhaps also here, just for clarification (we have way to many circular references..)
perhaps: 
http://linux-multimedia-studio-lmms.996328.n3.nabble.com/gitHub-perhaps-using-hash-reference-somewhat-less-td11830.html
not to bash in any direction at all..

Unfortunately, yes -BlueCat and many others still hang on reload

**Comment by PhysSong** [comment]
@musikBear Tested, seems to be fixed in rc4. If you can still reproduce this in rc4, please feel free to request reopening. :smile:

**Comment by musikBear** [comment]
@PhysSong Yes RC2 fixed several VSTs issues. I made a post about all those i retested with success. Blue-cat-suit was among those!
https://github.com/LMMS/lmms/issues/493#issuecomment-328923662
Asa an official release is ..well released, i will remove all the working ones from the wiki's *no-go-list*, and add them to *tested-working* vst
But as long as 1.1.3 is last official, it is to early.

**Comment by tresf** [comment]
@musikBear just add a note that some VSTs are 1.2.0 or higher.

**Comment by musikBear** [comment]
> @musikBear just add a note that some VSTs are 1.2.0 or higher.

Yes, that would be an idea, but what is the 1.2.0 final release actually has some forced regression, for other necessary reasons, then the confusion is total.

**Comment by tresf** [comment]
> Yes, that would be an idea, but what is the 1.2.0 final release actually has some forced regression, for other necessary reasons, then the confusion is total

What?  It's not an idea, it's a solution.  You said the following: 

> But as long as 1.1.3 is last official, it is to early.

I'm stating, no, it's not too early.  Just document it.

**Comment by musikBear** [comment]
Yes Sir! 🖖
